# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: build verification

on:
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v3
    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0'
    - name: Create Secrets File
      run: |
        echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> Secrets.xcconfig
        echo "GCM_SENDER_ID=${{ secrets.GCM_SENDER_ID }}" >> Secrets.xcconfig
        echo "GOOGLE_APP_ID=${{ secrets.GOOGLE_APP_ID }}" >> Secrets.xcconfig
        echo "REVERSED_CLIENT_ID=${{ secrets.REVERSED_CLIENT_ID }}" >> Secrets.xcconfig
    - name: Move Secrets File to Resources
      run: |
        mv Secrets.xcconfig pins/Resources/
    - name: Print GoogleService-Info.plist
      run: cat pins/Resources/GoogleService-Info.plist
    - name: Print xcconfig
      run: cat pins/Resources/Secrets.xcconfig
    - name: Build & Test Xcode
      run: |
        xcodebuild clean test -project pins.xcodeproj \
        -scheme Release \
        -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2'
