# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: build verification

on:
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Create Secrets File
      run: |
        echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> Secrets.xcconfig
        echo "GCM_SENDER_ID=${{ secrets.GCM_SENDER_ID }}" >> Secrets.xcconfig
        echo "GOOGLE_APP_ID=${{ secrets.GOOGLE_APP_ID }}" >> Secrets.xcconfig
        echo "REVERSED_CLIENT_ID=${{ secrets.REVERSED_CLIENT_ID }}" >> Secrets.xcconfig
    - name: Print Current Working Directory
      run: pwd
    - name: Move Secrets File to Resources
      run: |
        mv Secrets.xcconfig pins/Resources/
    - name: Update GoogleService-Info.plist
      run: |
        PLIST=pins/Resources/GoogleService-Info.plist
        /usr/libexec/PlistBuddy -c "Set :API_KEY ${{ secrets.GOOGLE_API_KEY }}" "$PLIST"
        /usr/libexec/PlistBuddy -c "Set :GCM_SENDER_ID ${{ secrets.GCM_SENDER_ID }}" "$PLIST"
        /usr/libexec/PlistBuddy -c "Set :GOOGLE_APP_ID ${{ secrets.GOOGLE_APP_ID }}" "$PLIST"
        /usr/libexec/PlistBuddy -c "Set :REVERSED_CLIENT_ID ${{ secrets.REVERSED_CLIENT_ID }}" "$PLIST"
    - name: Build Xcode
      run: |
        xcodebuild clean test -project pins.xcodeproj \
        -scheme Release \
        -destination 'platform=iOS Simulator,name=iPhone 13,OS=latest'
